package gitx

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	hookBegin = "# keel:begin"
	hookEnd   = "# keel:end"
)

// HookName 是 keel 会安装的两个 git hook。
type HookName string

const (
	PreCommit HookName = "pre-commit"
	CommitMsg HookName = "commit-msg"
)

// hookBody 是 keel 段的内容。
//
// 关键契约：keel 装好但检查失败时必须传播非零退出码。
// 旧设计写的是 `command -v keel && keel check || true`，
// `|| true` 会把失败吞成 0，两道提交检查全部失效
// （docs/design/fixtures/git-hook-exit 复现过）。
func hookBody(h HookName) string {
	switch h {
	case PreCommit:
		return `if command -v keel >/dev/null 2>&1; then
  keel check --quiet --target index || exit $?
fi`
	case CommitMsg:
		return `if command -v keel >/dev/null 2>&1; then
  keel check --quiet --target commit-msg --commit-msg "$1" || exit $?
fi`
	}
	return ""
}

// HookScript 返回全新安装时写入的完整脚本。
func HookScript(h HookName) string {
	return "#!/bin/sh\n" + hookBegin + "\n" + hookBody(h) + "\n" + hookEnd + "\n"
}

// HookStatus 是一个 hook 的当前情况。
type HookStatus string

const (
	// HookAbsent 还没有这个 hook。
	HookAbsent HookStatus = "absent"
	// HookManaged 由 keel 装的，可以安全更新。
	HookManaged HookStatus = "managed"
	// HookForeignShell 是别人的 POSIX shell hook，可以用 --adopt-hooks 串联。
	HookForeignShell HookStatus = "foreign-shell"
	// HookForeignOther 是非 shell 或由 hook 管理器接管的，keel 不碰。
	HookForeignOther HookStatus = "foreign-other"
)

// HookPlan 描述一个 hook 的安装计划。
type HookPlan struct {
	Name    HookName
	Path    string
	Status  HookStatus
	Detail  string
	Action  string // install | update | chain | skip
	Blocked bool   // 需要人介入
}

// HooksDir 返回 hook 实际生效的目录，认 core.hooksPath 与 worktree。
func (r *Repo) HooksDir() (string, error) {
	if p, err := r.git("config", "--get", "core.hooksPath"); err == nil {
		p = strings.TrimSpace(p)
		if p != "" {
			if !filepath.IsAbs(p) {
				p = filepath.Join(r.Root, p)
			}
			return p, nil
		}
	}
	if r.CommonDir == "" {
		return "", fmt.Errorf("找不到 git 目录")
	}
	return filepath.Join(r.CommonDir, "hooks"), nil
}

// PlanHooks 检查每个 hook 的现状，不写任何文件。
func (r *Repo) PlanHooks() ([]HookPlan, error) {
	dir, err := r.HooksDir()
	if err != nil {
		return nil, err
	}
	var plans []HookPlan
	for _, h := range []HookName{PreCommit, CommitMsg} {
		p := HookPlan{Name: h, Path: filepath.Join(dir, string(h))}
		data, err := os.ReadFile(p.Path)
		switch {
		case os.IsNotExist(err):
			p.Status, p.Action = HookAbsent, "install"
		case err != nil:
			return nil, err
		default:
			content := string(data)
			switch {
			case strings.Contains(content, hookBegin):
				p.Status, p.Action = HookManaged, "update"
			case detectManager(content) != "":
				p.Status, p.Action, p.Blocked = HookForeignOther, "skip", true
				p.Detail = fmt.Sprintf("已被 %s 接管；请在它的配置里加一步 `keel check --target %s`",
					detectManager(content), targetFor(h))
			case isPOSIXShell(content):
				p.Status, p.Action, p.Blocked = HookForeignShell, "chain", true
				p.Detail = "已有自定义 shell hook；用 --adopt-hooks 让 keel 串联（原脚本移到 " +
					string(h) + ".keel-local 并先执行）"
			default:
				p.Status, p.Action, p.Blocked = HookForeignOther, "skip", true
				p.Detail = "已有非 shell hook，keel 不会改写；请自行调用 `keel check --target " +
					targetFor(h) + "`"
			}
		}
		plans = append(plans, p)
	}
	sort.Slice(plans, func(i, j int) bool { return plans[i].Name < plans[j].Name })
	return plans, nil
}

func targetFor(h HookName) string {
	if h == CommitMsg {
		return "commit-msg --commit-msg \"$1\""
	}
	return "index"
}

func detectManager(content string) string {
	for marker, name := range map[string]string{
		"husky":                 "husky",
		"lefthook":              "lefthook",
		"pre-commit.com":        "pre-commit 框架",
		"INSTALL_PYTHON":        "pre-commit 框架",
		"_/husky.sh":            "husky",
		"lint-staged":           "lint-staged",
		"generated by lefthook": "lefthook",
	} {
		if strings.Contains(content, marker) {
			return name
		}
	}
	return ""
}

func isPOSIXShell(content string) bool {
	line := content
	if i := strings.IndexByte(content, '\n'); i >= 0 {
		line = content[:i]
	}
	line = strings.TrimSpace(line)
	if !strings.HasPrefix(line, "#!") {
		return false
	}
	return strings.Contains(line, "/sh") || strings.Contains(line, "/bash") ||
		strings.Contains(line, "env sh") || strings.Contains(line, "env bash")
}

// InstallHooks 按计划安装。adopt 为 true 时串联已有的 shell hook。
// 任何一个 hook 需要人介入且没被 adopt 覆盖时返回错误，不静默跳过。
func (r *Repo) InstallHooks(adopt bool) ([]HookPlan, error) {
	plans, err := r.PlanHooks()
	if err != nil {
		return nil, err
	}
	dir, err := r.HooksDir()
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}

	var blocked []string
	for i := range plans {
		p := &plans[i]
		switch {
		case p.Status == HookAbsent || p.Status == HookManaged:
			if err := writeExecutable(p.Path, HookScript(p.Name)); err != nil {
				return plans, err
			}
			p.Blocked = false
		case p.Status == HookForeignShell && adopt:
			local := p.Path + ".keel-local"
			if _, err := os.Stat(local); err == nil {
				return plans, fmt.Errorf("%s 已存在，先手工确认后再 --adopt-hooks", local)
			}
			if err := os.Rename(p.Path, local); err != nil {
				return plans, err
			}
			script := "#!/bin/sh\n" + hookBegin + "\n" +
				"# 先跑原有 hook，它失败就直接失败；再跑 keel。\n" +
				`if [ -x "$0.keel-local" ]; then
  "$0.keel-local" "$@" || exit $?
fi
` + hookBody(p.Name) + "\n" + hookEnd + "\n"
			if err := writeExecutable(p.Path, script); err != nil {
				return plans, err
			}
			p.Action = "chain"
			p.Blocked = false
			p.Detail = "原脚本已移到 " + filepath.Base(local) + "，由新 hook 先调用"
		default:
			blocked = append(blocked, string(p.Name)+"："+p.Detail)
		}
	}
	if len(blocked) > 0 {
		return plans, fmt.Errorf("以下 git hook 需要人来接：\n  %s\n（确认无需本地 hook 就用 --no-hooks；合并门禁请走 CI）",
			strings.Join(blocked, "\n  "))
	}
	return plans, nil
}

func writeExecutable(path, content string) error {
	tmp := path + ".keel-tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o755); err != nil {
		return err
	}
	if err := os.Chmod(tmp, 0o755); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return os.Rename(tmp, path)
}

// HookRemoval 描述退出（keel deinit）时对一个 hook 的处理计划。
//
// 和安装一样先规划再动手：含 keel 标记的才是 keel 的；去掉 keel 段之后什么都不剩
// 就删（串联过的把 .keel-local 换回去），还剩东西就只去掉 keel 段。
// 不含标记的是别人的，一个字节不动。
type HookRemoval struct {
	Name    HookName
	Path    string
	Action  string // restore | delete | trim | keep | none
	Detail  string
	Blocked bool // 需要人来接，不能自动处理

	trimmed string // Action == trim 时要写回的内容
}

// PlanRemoveHooks 检查每个 hook 退出时该怎么处理，不写任何文件。
func (r *Repo) PlanRemoveHooks() ([]HookRemoval, error) {
	dir, err := r.HooksDir()
	if err != nil {
		return nil, err
	}
	var plans []HookRemoval
	for _, h := range []HookName{PreCommit, CommitMsg} {
		p := HookRemoval{Name: h, Path: filepath.Join(dir, string(h))}
		local := p.Path + ".keel-local"
		_, lerr := os.Stat(local)
		hasLocal := lerr == nil

		data, err := os.ReadFile(p.Path)
		switch {
		case os.IsNotExist(err):
			p.Action = "none"
		case err != nil:
			return nil, err
		case !strings.Contains(string(data), hookBegin):
			p.Action = "keep"
			if m := detectManager(string(data)); m != "" {
				p.Detail = fmt.Sprintf("由 %s 管理；它的配置里若有 `keel check` 那一步，请自己删", m)
			} else {
				p.Detail = "不是 keel 装的，没动"
			}
		default:
			rest, serr := stripHookBlock(string(data))
			switch {
			case serr != nil:
				p.Action, p.Blocked, p.Detail = "keep", true, serr.Error()
			case hookRemainderEmpty(rest) && hasLocal:
				p.Action, p.Detail = "restore", "原脚本从 "+filepath.Base(local)+" 换回"
			case hookRemainderEmpty(rest):
				p.Action = "delete"
			case hasLocal:
				p.Action, p.Blocked = "keep", true
				p.Detail = "keel 段之外有手写内容，而 " + filepath.Base(local) + " 也还在；请手工合并后再退出"
			default:
				p.Action, p.Detail, p.trimmed = "trim", "去掉 keel 段，其余内容保留", rest
			}
		}
		plans = append(plans, p)
	}
	sort.Slice(plans, func(i, j int) bool { return plans[i].Name < plans[j].Name })
	return plans, nil
}

// RemoveHooks 按计划执行。有 Blocked 的计划时什么都不做，直接报错。
func (r *Repo) RemoveHooks(plans []HookRemoval) error {
	for _, p := range plans {
		if p.Blocked {
			return fmt.Errorf("hook %s 需要人来接：%s", p.Name, p.Detail)
		}
	}
	for _, p := range plans {
		switch p.Action {
		case "delete":
			if err := os.Remove(p.Path); err != nil && !os.IsNotExist(err) {
				return err
			}
		case "restore":
			if err := os.Remove(p.Path); err != nil && !os.IsNotExist(err) {
				return err
			}
			if err := os.Rename(p.Path+".keel-local", p.Path); err != nil {
				return err
			}
		case "trim":
			if err := writeExecutable(p.Path, p.trimmed); err != nil {
				return err
			}
		}
	}
	return nil
}

// stripHookBlock 去掉 keel 段（含标记），两侧内容接回。只找到半个标记就报错。
func stripHookBlock(content string) (string, error) {
	i := strings.Index(content, hookBegin)
	j := strings.Index(content, hookEnd)
	switch {
	case i < 0 || j < 0:
		return "", fmt.Errorf("只找到半个 keel 标记（begin=%v end=%v），请手工清理", i >= 0, j >= 0)
	case j < i:
		return "", fmt.Errorf("keel 标记顺序颠倒，请手工清理")
	}
	before := strings.TrimRight(content[:i], "\n")
	after := strings.TrimLeft(content[j+len(hookEnd):], "\n")
	out := before
	if before != "" && after != "" {
		out += "\n\n" + after
	} else {
		out += after
	}
	if out != "" && !strings.HasSuffix(out, "\n") {
		out += "\n"
	}
	return out, nil
}

// hookRemainderEmpty 报告去掉 keel 段之后是否只剩 shebang 和空白。
func hookRemainderEmpty(rest string) bool {
	lines := strings.SplitN(rest, "\n", 2)
	if len(lines) > 0 && strings.HasPrefix(lines[0], "#!") {
		rest = ""
		if len(lines) == 2 {
			rest = lines[1]
		}
	}
	return strings.TrimSpace(rest) == ""
}

// WorktreeCount 返回这个仓库有几个工作树（含主仓库）。hook 是仓库级的，退出时要提醒。
func (r *Repo) WorktreeCount() int {
	out, err := r.git("worktree", "list", "--porcelain")
	if err != nil {
		return 1
	}
	n := 0
	for _, line := range strings.Split(out, "\n") {
		if strings.HasPrefix(line, "worktree ") {
			n++
		}
	}
	if n == 0 {
		return 1
	}
	return n
}

// StatusPorcelain 返回某个路径下 git status --porcelain 的输出（含未跟踪文件）。
// 空串表示这条路径在 git 里是干净的。
func (r *Repo) StatusPorcelain(path string) (string, error) {
	out, err := r.git("status", "--porcelain", "--untracked-files=all", "--", path)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(out), nil
}
