package gitx

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	hookBegin = "# keel:begin"
	hookEnd   = "# keel:end"
)

// HookName 是 keel 会安装的两个 git hook。
type HookName string

const (
	PreCommit HookName = "pre-commit"
	CommitMsg HookName = "commit-msg"
)

// hookBody 是 keel 段的内容。
//
// 关键契约：keel 装好但检查失败时必须传播非零退出码。
// 旧设计写的是 `command -v keel && keel check || true`，
// `|| true` 会把失败吞成 0，两道提交检查全部失效
// （docs/design/fixtures/git-hook-exit 复现过）。
func hookBody(h HookName) string {
	switch h {
	case PreCommit:
		return `if command -v keel >/dev/null 2>&1; then
  keel check --quiet --target index || exit $?
fi`
	case CommitMsg:
		return `if command -v keel >/dev/null 2>&1; then
  keel check --quiet --target commit-msg --commit-msg "$1" || exit $?
fi`
	}
	return ""
}

// HookScript 返回全新安装时写入的完整脚本。
func HookScript(h HookName) string {
	return "#!/bin/sh\n" + hookBegin + "\n" + hookBody(h) + "\n" + hookEnd + "\n"
}

// HookStatus 是一个 hook 的当前情况。
type HookStatus string

const (
	// HookAbsent 还没有这个 hook。
	HookAbsent HookStatus = "absent"
	// HookManaged 由 keel 装的，可以安全更新。
	HookManaged HookStatus = "managed"
	// HookForeignShell 是别人的 POSIX shell hook，可以用 --adopt-hooks 串联。
	HookForeignShell HookStatus = "foreign-shell"
	// HookForeignOther 是非 shell 或由 hook 管理器接管的，keel 不碰。
	HookForeignOther HookStatus = "foreign-other"
)

// HookPlan 描述一个 hook 的安装计划。
type HookPlan struct {
	Name    HookName
	Path    string
	Status  HookStatus
	Detail  string
	Action  string // install | update | chain | skip
	Blocked bool   // 需要人介入
}

// HooksDir 返回 hook 实际生效的目录，认 core.hooksPath 与 worktree。
func (r *Repo) HooksDir() (string, error) {
	if p, err := r.git("config", "--get", "core.hooksPath"); err == nil {
		p = strings.TrimSpace(p)
		if p != "" {
			if !filepath.IsAbs(p) {
				p = filepath.Join(r.Root, p)
			}
			return p, nil
		}
	}
	if r.CommonDir == "" {
		return "", fmt.Errorf("找不到 git 目录")
	}
	return filepath.Join(r.CommonDir, "hooks"), nil
}

// PlanHooks 检查每个 hook 的现状，不写任何文件。
func (r *Repo) PlanHooks() ([]HookPlan, error) {
	dir, err := r.HooksDir()
	if err != nil {
		return nil, err
	}
	var plans []HookPlan
	for _, h := range []HookName{PreCommit, CommitMsg} {
		p := HookPlan{Name: h, Path: filepath.Join(dir, string(h))}
		data, err := os.ReadFile(p.Path)
		switch {
		case os.IsNotExist(err):
			p.Status, p.Action = HookAbsent, "install"
		case err != nil:
			return nil, err
		default:
			content := string(data)
			switch {
			case strings.Contains(content, hookBegin):
				p.Status, p.Action = HookManaged, "update"
			case detectManager(content) != "":
				p.Status, p.Action, p.Blocked = HookForeignOther, "skip", true
				p.Detail = fmt.Sprintf("已被 %s 接管；请在它的配置里加一步 `keel check --target %s`",
					detectManager(content), targetFor(h))
			case isPOSIXShell(content):
				p.Status, p.Action, p.Blocked = HookForeignShell, "chain", true
				p.Detail = "已有自定义 shell hook；用 --adopt-hooks 让 keel 串联（原脚本移到 " +
					string(h) + ".keel-local 并先执行）"
			default:
				p.Status, p.Action, p.Blocked = HookForeignOther, "skip", true
				p.Detail = "已有非 shell hook，keel 不会改写；请自行调用 `keel check --target " +
					targetFor(h) + "`"
			}
		}
		plans = append(plans, p)
	}
	sort.Slice(plans, func(i, j int) bool { return plans[i].Name < plans[j].Name })
	return plans, nil
}

func targetFor(h HookName) string {
	if h == CommitMsg {
		return "commit-msg --commit-msg \"$1\""
	}
	return "index"
}

func detectManager(content string) string {
	for marker, name := range map[string]string{
		"husky":                 "husky",
		"lefthook":              "lefthook",
		"pre-commit.com":        "pre-commit 框架",
		"INSTALL_PYTHON":        "pre-commit 框架",
		"_/husky.sh":            "husky",
		"lint-staged":           "lint-staged",
		"generated by lefthook": "lefthook",
	} {
		if strings.Contains(content, marker) {
			return name
		}
	}
	return ""
}

func isPOSIXShell(content string) bool {
	line := content
	if i := strings.IndexByte(content, '\n'); i >= 0 {
		line = content[:i]
	}
	line = strings.TrimSpace(line)
	if !strings.HasPrefix(line, "#!") {
		return false
	}
	return strings.Contains(line, "/sh") || strings.Contains(line, "/bash") ||
		strings.Contains(line, "env sh") || strings.Contains(line, "env bash")
}

// InstallHooks 按计划安装。adopt 为 true 时串联已有的 shell hook。
// 任何一个 hook 需要人介入且没被 adopt 覆盖时返回错误，不静默跳过。
func (r *Repo) InstallHooks(adopt bool) ([]HookPlan, error) {
	plans, err := r.PlanHooks()
	if err != nil {
		return nil, err
	}
	dir, err := r.HooksDir()
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}

	var blocked []string
	for i := range plans {
		p := &plans[i]
		switch {
		case p.Status == HookAbsent || p.Status == HookManaged:
			if err := writeExecutable(p.Path, HookScript(p.Name)); err != nil {
				return plans, err
			}
			p.Blocked = false
		case p.Status == HookForeignShell && adopt:
			local := p.Path + ".keel-local"
			if _, err := os.Stat(local); err == nil {
				return plans, fmt.Errorf("%s 已存在，先手工确认后再 --adopt-hooks", local)
			}
			if err := os.Rename(p.Path, local); err != nil {
				return plans, err
			}
			script := "#!/bin/sh\n" + hookBegin + "\n" +
				"# 先跑原有 hook，它失败就直接失败；再跑 keel。\n" +
				`if [ -x "$0.keel-local" ]; then
  "$0.keel-local" "$@" || exit $?
fi
` + hookBody(p.Name) + "\n" + hookEnd + "\n"
			if err := writeExecutable(p.Path, script); err != nil {
				return plans, err
			}
			p.Action = "chain"
			p.Blocked = false
			p.Detail = "原脚本已移到 " + filepath.Base(local) + "，由新 hook 先调用"
		default:
			blocked = append(blocked, string(p.Name)+"："+p.Detail)
		}
	}
	if len(blocked) > 0 {
		return plans, fmt.Errorf("以下 git hook 需要人来接：\n  %s\n（确认无需本地 hook 就用 --no-hooks；合并门禁请走 CI）",
			strings.Join(blocked, "\n  "))
	}
	return plans, nil
}

func writeExecutable(path, content string) error {
	tmp := path + ".keel-tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o755); err != nil {
		return err
	}
	if err := os.Chmod(tmp, 0o755); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return os.Rename(tmp, path)
}
